name: login_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4

  ## -- STATE MANAGEMENT
  get: ^4.6.5

  ## -- OnBoarding PACKAGES
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

  ## -- OTP TEXT FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1

  ## -- FIREBASE PACKAGES
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.1.5


  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.6
  line_awesome_flutter: ^2.0.0
  flutter_native_splash: ^2.3.3
  flutter_svg: ^2.0.7
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/

# Splash screen has been added in the 'splash.yaml' file in main project directory